# Tell Spring to use H2 in-memory
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Allow Hibernate to automatically create the tables based on your @Entity
spring.jpa.hibernate.ddl-auto=update
# Optional: See the SQL Spring is running in your console
spring.jpa.show-sql=true

# Enable the web-based UI
spring.h2.console.enabled=true
# The URL path where to access the UI
spring.h2.console.path=/h2-console

spring.jpa.defer-datasource-initialization=true